{"issue_type": "request_error", "error_msg": "HTTPConnectionPool(host='ci.grottoes.va.us', port=80): Max retries exceeded with url: /robots.txt (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb7a84bf520>, 'Connection to ci.grottoes.va.us timed out. (connect timeout=15)'))"}