{"issue_type": "request_error", "error_msg": "HTTPConnectionPool(host='co.fayette.pa.us', port=80): Max retries exceeded with url: /robots.txt (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f29417c2430>, 'Connection to co.fayette.pa.us timed out. (connect timeout=15)'))"}