{"issue_type": "request_error", "error_msg": "HTTPConnectionPool(host='co.madison.tn.us', port=80): Max retries exceeded with url: /robots.txt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8721d750d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"}