{"issue_type": "request_error", "error_msg": "HTTPConnectionPool(host='cranstonri.com', port=80): Max retries exceeded with url: /robots.txt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa08a5a3d00>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"}