{"issue_type": "request_error", "error_msg": "HTTPConnectionPool(host='azrangers.gov', port=80): Max retries exceeded with url: /robots.txt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fad8764c280>: Failed to establish a new connection: [Errno -2] Name or service not known'))"}