{"issue_type": "request_error", "error_msg": "HTTPConnectionPool(host='hillsborova.gov', port=80): Max retries exceeded with url: /robots.txt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2cb0848f10>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"}